export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="chill"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

DISABLE_MAGIC_FUNCTIONS=true

# ENABLE_CORRECTION="true"

plugins=(git
colorize
zsh-autosuggestions
history-search-multi-word)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias qgc="~/Downloads/QGroundControl.AppImage"
alias etcher="~/Downloads/balenaEtcher-1.5.116-x64.AppImage"
alias cubemx="~/STM32CubeMX/STM32CubeMX"
alias tmuxconfig="tmux source-file ~/.tmux.conf"
alias zshconfig="source ~/.zshrc"
alias ssh-new="ssh-keygen -f ~/.ssh/known_hosts -R"
alias gco="git checkout "

# alias ohmyzsh="mate ~/.oh-my-zsh"
