export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="chill"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

DISABLE_MAGIC_FUNCTIONS=true

# ENABLE_CORRECTION="true"

plugins=(git
colorize
zsh-autosuggestions
history-search-multi-word)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias tmuxconfig="tmux source-file ~/.tmux.conf"
alias zshconfig="source ~/.zshrc"
alias ssh-new="ssh-keygen -f ~/.ssh/known_hosts -R"
alias gco="git checkout "
alias gti="git"
alias got="git"
alias windows="virtualbox /media/daria/drs/Windows\ 10\ For\ Flasher\ Clone/Windows\ 10\ For\ Flasher\ Clone/Windows\ 10\ For\ Flasher\ Clone.vbox"
alias open="nautilus"
alias git-clean="git branch | grep -vw dev | grep -vw master | xargs git branch -D"

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# alias ohmyzsh="mate ~/.oh-my-zsh"

realPS1="$PS1"
changed=false

hide() {

   $changed && {

      PS1="%n (normal) in %~> "
      #Or
      PS1="$realPS1"

      changed=false
      : # <-- It might be not necessary add this `:`. This one
        #represents a zero-status code (or successful).

   } || {
      PS1="%n (hidden)> "
      changed=true
   }
}

bindkey -s "^H" 'hide^M'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
